{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
<label>{'Media player type'|i18n( 'design/standard/class/datatype' )}:</label>


<div class="block">
<label>{'Max file size'|i18n( 'design/standard/class/datatype' )}:</label>
<input type="text" name="ContentClass_ezflowmedia_max_filesize_{$class_attribute.id}" value="{$class_attribute.data_int1}" size="5" maxlength="5" />&nbsp;MB
</div>
